name: Build & Push Docker Image

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 推送 GHCR 需要
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/OWNER/my-react:latest
          cache-from: type=registry,ref=ghcr.io/OWNER/my-react:buildcache
          cache-to: type=registry,ref=ghcr.io/OWNER/my-react:buildcache,mode=max

      - name: Call Webhook for Deploy
        run: |
          curl -X POST http://dokploy.micromatrix.org:3000/api/deploy/qoHcAnGUyM7qWwJ17Ad1f \
          -H "Content-Type: application/json" \
          -d '{"status": "success", "message": "Docker image build and push completed"}'
